version: '3.3'

services:

  db:
    container_name: database
    image: postgres:14
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    healthcheck:
      test: echo 'SELECT 1;' | psql --dbname=${POSTGRES_DB} --username=${POSTGRES_USER} --no-password >/dev/null
      interval: 2s
      timeout: 2s
      retries: 30

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - ${PGAMIN_PORT}:80
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: bash -c "alembic -c backend/alembic.ini upgrade head && uvicorn backend.main:app --host 0.0.0.0 --port ${APPS_PORT} --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
